### PR TITLE
Added most styles

### PR DESCRIPTION
**Pull request by Kakalanp**
- Adding some quality of life content in JavaScript (now you can press enter to focus next element in addition).

- The page now looks better thanks to CSS!

-Improved font-family for titles and subtitles.

### CODE REVIEW

**Review by Ghiftee — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽  @Kakalanp

Good job working on the project so far! 
✔️ App design is great
✔️ There are no linter errors
However, there are some issues that you need to work on to go to the next project but you are almost there!



## Required Changes ♻️
- [ ] It would be great if you add all that's needed to run the app with the API(s) it consumes. It should have instructions about where and how to generate any necessary keys, credentials, how to set, store, and generate them(if necessary) on the README file. It's an easy requirement but important to have a more professional project
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Kakalanp** [comment]
## Hey @Ghiftee! 👋

Thank you for the review you left me! Although, I'd love you to clarify the required changes a little more. 🔍 

The API I'm using only needs an input value for name and score in case of adding an item, otherwise it should display the contents without any further requirements. 
As for the dependencies, the README file stated that you only need to run a few commands (listed there) to install them, and then you should be able to run it normally afterwards.

I'd love to hear back from you soon to continue the review process. ✨  Thank you!

**Comment by mke2111** [comment]
Project Under Second Opinion Review.
Kindly wait for a response. 😄

**Review by mke2111 — COMMENTED** [review]
Hello @Kakalanp  👋,

_This is an additional review as a result of the second opinion request._

For the leaderboard API, your app is running just fine without the need to generate any API key. You would otherwise have to add these details if this wasn't the case. So, you may consider this requested change as optional.

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)

Keep rocking 🚀!

**Review by Cathella — APPROVED** [review]
## 🔥 Status: Approved 🟢

### Hi @Kakalanp 👋🏻, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kakalanp** [comment]
### Thanks a lot to all code reviewers in this project, I'll be merging the changes right now!

**Pull request merged**
